
using System.ComponentModel.DataAnnotations;
using TennisScores.Domain.Enums;

namespace TennisScores.Domain.Entities;

public class Player
{
    public Guid Id { get; set; } //= Guid.NewGuid(); Generated by EF Core

    [Required]
    public string FirstName { get; set; } = string.Empty;

    [Required]
    public string LastName { get; set; } = string.Empty;

    public FftRanking? FftRanking { get; set; } // French Tennis Federation ranking, if applicable e.g. "15/4

    public string? Nationality { get; set; }

    public DateTime? BirthDate { get; set; } 

    public ICollection<Match> MatchesAsPlayer1 { get; set; } = new List<Match>();
    public ICollection<Match> MatchesAsPlayer2 { get; set; } = new List<Match>();
}